# CrewAI Tasks Configuration for YouTube Blog Automation
# Defines the sequential workflow for content creation

research_videos_task:
  description: >
    Research and find the top 3 most recent, high-quality YouTube videos related to the topic: {topic}.
    
    Detailed Steps:
    1. Use YouTube Data API to search for recent videos on the specified topic
    2. Filter results by upload date (prioritize videos from last 7-30 days)
    3. Evaluate videos based on:
       - Content relevance to the topic
       - Video duration (prefer 10+ minutes for substantial content)
       - Channel credibility and subscriber count
       - View count and engagement metrics
    4. Select the top 3 videos that best match the criteria
    5. Extract full transcripts from each selected video using YouTube Transcript API
    6. Analyze transcript quality and content depth
    7. Identify key themes, insights, and unique perspectives from each video
    8. Compile comprehensive research findings in structured format
    
    Quality Requirements:
    - Videos must have clear, substantial transcripts (avoid music-only or low-content videos)
    - Prefer videos with good audio quality and minimal background noise
    - Ensure diversity of perspectives across the 3 selected videos
    - Verify transcripts contain actionable insights and valuable information
    
  expected_output: >
    A comprehensive research report in Markdown format containing:
    - Executive summary of findings for the topic
    - Detailed information for each of the 3 videos:
      * Video title, URL, upload date, duration, and channel information
      * Full transcript with timestamps
      * Content quality assessment and relevance score
      * Key insights and main themes identified
      * Unique perspectives or angles presented
    - Cross-video analysis identifying common themes and contrasting viewpoints
    - Recommendations for primary focus areas for the blog post
    - Source credibility assessment for each video
    
  agent: youtube_researcher
  output_file: "output/research/video_research_{topic}.md"

write_blog_post_task:
  description: >
    Create a comprehensive, engaging blog post based on the video research data from the previous task.
    Target 6-10 minute read time (approximately 1,500-2,500 words) with high-quality, valuable content.
    
    Content Requirements:
    - Write in an engaging, conversational tone that builds authority
    - Target read time: 6-10 minutes (1,500-2,500 words)
    - Integrate insights from all 3 researched videos seamlessly
    - Create original content that adds value beyond the source material
    - Include compelling examples, explanations, and actionable insights
    - Maintain logical flow and strong narrative structure
    - Optimize for SEO with natural keyword integration
    - Include engaging hooks, transitions, and a strong conclusion
    
    Structure Requirements:
    - Compelling, SEO-optimized title (50-60 characters)
    - Engaging meta description (150-160 characters)
    - Strong introduction with hook and clear value proposition
    - 4-6 main sections with descriptive H2 headings
    - 2-3 subsections per main section with H3 headings
    - Conclusion with key takeaways and call-to-action
    - Proper attribution and references to source videos
    
    SEO Optimization:
    - Natural integration of target keywords throughout content
    - Proper heading hierarchy (H1, H2, H3)
    - Include related keywords and semantic variations
    - Optimize for featured snippets with clear, direct answers
    - Add internal linking opportunities where relevant
    
  expected_output: >
    A complete, publication-ready blog post in Markdown format including:
    - SEO-optimized title and meta description
    - Well-structured content with proper heading hierarchy
    - 1,500-2,500 word count with engaging, valuable content
    - Natural integration of insights from all source videos
    - Compelling introduction that hooks readers immediately
    - Logical section progression with smooth transitions
    - Strong conclusion with clear takeaways and next steps
    - Proper citations and attribution to source videos
    - Suggestions for image placement throughout the content
    
  agent: content_writer
  context:
    - research_videos_task
  output_file: "output/content/blog_post_{topic}.md"

curate_images_task:
  description: >
    Search for and curate high-quality stock images to enhance the blog post content.
    Focus on finding professional, relevant imagery that supports the written content
    and improves reader engagement and comprehension.
    
    Image Requirements:
    - Search for 1 featured image for the blog post header/social sharing
    - Find 3-4 supporting images for main content sections
    - Ensure all images are relevant to the topic and specific content sections
    - Select high-resolution, professional-quality photographs
    - Verify proper licensing for commercial/editorial use
    - Maintain visual consistency and professional appearance
    
    Technical Specifications:
    - Featured image: High resolution, social media optimized (1200x630px preferred)
    - Supporting images: Web-optimized resolution (800x450px recommended)
    - File formats: JPG or PNG as appropriate
    - Professional stock photography preferred over illustrations
    - Ensure images load quickly while maintaining quality
    
    SEO and Attribution:
    - Generate descriptive, SEO-friendly alt text for each image
    - Create appropriate file names with relevant keywords
    - Provide proper attribution for photographers and sources
    - Include usage rights and licensing information
    - Suggest optimal placement within the blog content structure
    
  expected_output: >
    A curated collection of stock images with complete metadata:
    - 1 high-quality featured image with social media optimization
    - 3-4 supporting images aligned with specific content sections
    - Comprehensive image metadata including:
      * Image URLs and download links
      * SEO-optimized alt text for each image
      * Descriptive file names with keywords
      * Photographer attribution and source information
      * Licensing and usage rights details
      * Recommended placement within blog content
      * Image dimensions and technical specifications
    - Visual style consistency report
    - Image optimization recommendations
    
  agent: image_curator
  context:
    - write_blog_post_task
  output_file: "output/images/image_collection_{topic}.json"

publish_content_task:
  description: >
    Format and publish the completed blog post with images to the Medium platform.
    Ensure proper formatting, metadata configuration, and optimal presentation
    for maximum reader engagement and platform algorithm performance.
    
    Publishing Requirements:
    - Format content according to Medium's best practices and guidelines
    - Upload and properly embed all curated images with attribution
    - Configure appropriate tags, categories, and publication settings
    - Set up proper SEO metadata including title, description, and canonical URLs
    - Ensure all links, formatting, and media elements work correctly
    - Schedule publication for optimal timing (or publish immediately if specified)
    
    Content Formatting:
    - Convert Markdown to Medium-compatible rich text formatting
    - Ensure proper heading hierarchy and text formatting
    - Embed images at optimal locations within the content flow
    - Add proper image captions and alt text for accessibility
    - Include photographer attributions for stock images
    - Format citations and references appropriately
    
    Metadata Configuration:
    - Set compelling title optimized for Medium's algorithm
    - Write engaging subtitle/description that encourages clicks
    - Select relevant tags (maximum 5) for discoverability
    - Configure publication settings (public/unlisted, etc.)
    - Set canonical URL if publishing to multiple platforms
    - Enable/configure comments and engagement settings
    
    Quality Assurance:
    - Verify all images display correctly and load quickly
    - Check all links and references work properly
    - Ensure proper formatting across different devices
    - Confirm all attribution and licensing requirements are met
    - Validate SEO elements are properly configured
    
  expected_output: >
    Comprehensive publication report including:
    - Medium post URL and publication confirmation
    - Publication timestamp and scheduling details
    - Configured metadata (title, tags, description, etc.)
    - Image upload and embedding confirmations
    - SEO configuration summary
    - Performance tracking setup details
    - Publication success/failure status with details
    - Post-publication checklist completion status
    - Engagement and analytics setup confirmation
    - Any errors or issues encountered during publishing
    
  agent: content_publisher
  context:
    - write_blog_post_task
    - curate_images_task
  output_file: "output/published/publication_report_{topic}.json"